import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Hero from "./_components/Hero";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin-ext"],weight : '500' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Hero />
        <Footer />
        </body>
    </html>
  );
}
